"""empty message

Revision ID: 2cc89f5acb61
Revises: 
Create Date: 2023-10-15 17:25:22.632130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc89f5acb61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoryId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'category', ['categoryId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoryId')

    # ### end Alembic commands ###
